function [] = polyTuneAll(nd)
%POLYTUNEALL Poly Tune All
%   polyTuneAll(nd) tunes polynomial for all properties.
%
%   See also sobSA.

%%
prop = { 'FPR'...
			'totMobCo2'...
			'totResCo2'...
			'largestPlume'...
			'meanPlume'...
			'WBHP'...
			'plumeNum'...
			'leakageRisk'...
			};
for i = 1:length(prop),
	if ~exist(['/Home/siv16/mas062/prjII/aPC/DATA/' num2str(nd) '/' prop{i} '_tuneNomial.mat'],'file'),polyTune(prop{i},nd);end
end
		
end
