%% Enceladus Startup
%
nm = mfilename('fullpath');
ix = strfind(nm, filesep);
if ~isempty(ix),
   enclD = nm(1 : ix(end));
else
   enclD = nm;
end
addpath(genpath(enclD));
% Amend MATLAB PATH to handle MRST implementation.

% $Date: 2010-02-05 17:16:46 +0100 (Fri, 05 Feb 2010) $
% $Revision: 3941 $
cd('C:\Users\meisama\Documents\PhD\SVN\simmatlab\trunk\utils');
p = strcat(ROOTDIR,                                   ...
           {                                          ...
            '',                                       ...
            'doc',                                    ...
            'examples',                               ...
           ['examples', filesep, '1ph'],              ...
           ['examples', filesep, '2ph'],              ...
           ['examples', filesep, 'grids'],            ...
            'gridprocessing',                         ...
           ['gridprocessing', filesep, 'testgrids'],  ...
           ['mex', filesep, 'opm-gridprocessing'],    ...
           ['mex', filesep, 'triangle'],              ...
            'params',                                 ...
           ['params', filesep, 'fluid'],              ...
           ['params', filesep, 'fluid', filesep, 'compressible'], ...
           ['params', filesep, 'fluid', filesep, 'incompressible'], ...
           ['params', filesep, 'fluid', filesep, 'utils'], ...
           ['params', filesep, 'rock'],               ...
           ['params', filesep, 'wells_and_bc'],       ...
            'plotting',                               ...
            'regression',                             ...
           ['regression', filesep, 'tests'],          ...
            'solvers',                                ...
           ['solvers', filesep, 'adjoint'],           ...
           ['solvers', filesep, 'adjoint', filesep, 'hessian'],     ...
           ['solvers', filesep, 'adjoint', filesep, 'objectives'],  ...
           ['solvers', filesep, 'adjoint', filesep, 'optimsecond'], ...
           ['solvers', filesep, 'adjoint', filesep, 'tests'],       ...           
           ['solvers', filesep, 'mimetic'],           ...
           ['solvers', filesep, 'mimetic', filesep, 'blackoil'], ...
           ['solvers', filesep, 'mimetic', filesep, 'utils'], ...
           ['solvers', filesep, 'mpfa'],              ...
           ['solvers', filesep, 'msmfem'],            ...
           ['solvers', filesep, 'msmfem', filesep, 'utils'], ...
           ['solvers', filesep, 'nuc'],               ...
           ['solvers', filesep, 'stokes-brinkman'],   ...
           ['solvers', filesep, 'stokes-brinkman', filesep, 'plotting'], ...
           ['solvers', filesep, 'tpfa'],              ...
           ['solvers', filesep, 'transport'],         ...
           ['solvers', filesep, 'transport', filesep, 'blackoil'], ...
           ['solvers', filesep, 'upscaling'],         ...
            'tests',                                  ...
           ['tests', filesep, 'blackoil'],            ...
           ['tests', filesep, 'stokes-brinkman'],     ...
            'utils',                                  ...
           ['utils', filesep, 'binio'],               ...
           ['utils', filesep, 'inout'],               ...
           ['utils', filesep, 'inout', filesep, 'eclipse' ], ...
           ['utils', filesep, 'inout', filesep, 'eclipse', filesep, 'deckinput'], ...
           ['utils', filesep, 'inout', filesep, 'eclipse', filesep, 'resultinput'], ...
           ['utils', filesep, 'units'],               ...
            'iterative_ms',                           ... % Integrate into package
           }, pathsep);
addpath([p{:}]);
clear p;
cd ..
