function [] = saPlt(nd)
%SAPLT Sensistivity Analysis Plots
%   saPlt() plots the total Sobol indices used in the sensitivity analysis.
%
%   See also sobSA.

%%
prop = { 'FPR'...
			'totMobCo2'...
			'totResCo2'...
			'largestPlume'...
			'meanPlume'...
			'WBHP'...
			'plumeNum'...
			'leakageRisk'...
			};
for i = 1:length(prop),
	sobSA(prop{i},nd);
end

			
end



