
function [] = aveAll(nd)
%AVEAll Average for All 
%	aveAll(nd) plots the average of all properties.
% 	
%	See also, aveRA, histRA, cdfRA, sobSA, polyTune, polyGen.
%

%%
prop = { 'FPR'...
                        'totMobCo2'...
                        'totResCo2'...
                        'largestPlume'...
                        'meanPlume'...
                        'WBHP'...
                        'plumeNum'...
                        'leakageRisk'...
                        };  
                    
for i = 1:length(prop),
    display(['Calculating and plotting the average for ' prop{i}]);
    aveRA(prop{i},nd);
end 
end
